# Generated by Django 4.2.2 on 2023-09-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='duedate_field',
            field=models.TextField(default='duedate'),
        ),
        migrations.AddField(
            model_name='config',
            name='issuetypes',
            field=models.TextField(default='Story'),
        ),
        migrations.AddField(
            model_name='config',
            name='startdate_field',
            field=models.TextField(default='customfield_10015'),
        ),
    ]
