# Generated by Django 4.2.2 on 2023-09-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_config_duedate_field_config_issuetypes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='jira_url',
            field=models.TextField(default='https://jiraps.atlassian.net'),
        ),
    ]
