# Generated by Django 4.2.2 on 2024-01-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_config_jira_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='token',
            field=models.BinaryField(),
        ),
    ]
